src/main/java/eu/europa/ec/dgc/gateway/entity/SignerInformationEntity.java, src/main/java/eu/europa/ec/dgc/gateway/entity/TrustedPartyEntity.java, src/main/resources/db/changelog/init-tables.xml
Increase Signature Column Size to 6000 for 4096 bit sized CMS signatures
=> Increase Column Size for Signatures

src/main/java/eu/europa/ec/dgc/gateway/service/SignerInformationService.java
We experienced an issue at validating CSCA when DSC was signed with 2048 Bit CA and only 4096 Bit CSCA are whitelisted. The validation crashes and gateway returns 500 error code.
This PR adds the thrown Exception to the catch block of .isSignatureValid() method to catch these exceptions and return correct ```false``` result.
=> Fix: CSCA Verification Error

src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/SignerCertificateController.java, src/main/java/eu/europa/ec/dgc/gateway/service/AuditService.java, src/test/java/eu/europa/ec/dgc/gateway/service/AuditServiceTest.java
The Audit Events are currently logging the .toString() of certificates.
I've changed it to use the hash of certificate.
=> Fix: Certificate Hash in Audit Events

src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/TrustListController.java
OpenAPI Spec for TrustList download filtered by type and country has a wrong parameter county.
=> Fix: Typo in OpenAPI Spec

src/main/java/eu/europa/ec/dgc/gateway/config/BouncyCastleConfig.java
Some MS had problems uploading certs signed with SHA256withRSASSA-PSS.
Adding BouncyCastle as SecurityProvider will fix this issue.
=> Fix: Add BouncyCastleProvider to JavaSecurity

README.md, src/main/java/eu/europa/ec/dgc/gateway/config/OpenApiConfig.java, src/main/resources/application-local.yml
This PR adds the ability to enter authentication headers (Cert-Hash and Cert-DN) when starting DGCG on your local machine.
To enable the feature the Spring-Profile ```local``` needs to be enabled.
This PR closes #62
=> Add Authentication Header to Swagger UI

src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/SignerCertificateController.java
This PR adds a new alias for the delete/revoke endpoint.
This Alias is introduced to support Load Balancers which are removing the payload when sending DELETE requests.
This PR closes #63
=> Add Alias for Delete/Revoke Endpoint

docs/software-design-dgc-gateway.md, src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/TrustListController.java
This PR adds log messages when keys (TrustLists) were downloaded by a country.
The amount of keys, the downloader country and (if provided) the type of certificates is logged.
=> Add Logging for Downloaded Keys

docs/software-design-dgc-gateway.md, src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/SignerCertificateController.java
The MDC Parameter "messages" creates a conflict with existing log message structure.
=> Fix MDC Parameter name for Verification Errors

src/main/java/eu/europa/ec/dgc/gateway/entity/SignerInformationEntity.java, src/main/java/eu/europa/ec/dgc/gateway/entity/TrustedPartyEntity.java, src/main/resources/db/changelog.xml, src/main/resources/db/changelog/add-unique-constraints.xml, src/main/resources/db/snapshot.json
This PR adds a missing Unique Constraint to both TrustedParty and SignerInformation entity.
This pr fixes #90
=> Add Unique Constraint to Thumbprint of TrustedParty and SignerInformation

src/main/java/eu/europa/ec/dgc/gateway/repository/ValidationRuleRepository.java, src/main/java/eu/europa/ec/dgc/gateway/service/ValidationRuleService.java, src/test/java/eu/europa/ec/dgc/gateway/restapi/controller/ValidationRuleIntegrationTest.java
This PR fixes the Bug that not all future valid rules will be downloaded when only rules which are valid in future exists and nur currently active rule.
This PR currently only contains a Unit-Test which is confirming this behaviour.
Implementation of the fix is still tbd.
=> Fix: Missing Download of Rules Valid only in Future

pom.xml, src/main/resources/db/changelog.xml, src/main/resources/db/changelog/fix-certificate-thumbprints.xml
This PR fixes the Certificate Thumbprint calculation. (Missing leading "00")
This PR also includes a Liquibase Changeset to repair invalid entities in the database.
closes #94
=> Fix Certificate Thumbprints

src/main/java/eu/europa/ec/dgc/gateway/config/ValidationRuleSchemaProvider.java
Out of the box, the gateway is configured to load the validation rule schema from within the classpath, rather than from a file on disk. This was resulting in a failure[1] as `ResourceUtils.getFile()` does not support loading from a classpath.
By switching to use `getURL().openStream()`, both classpath and filesystem loads will work correctly.
[1]: `Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'validationRuleSchemaProvider': Invocation of init method failed; nested exception is java.io.FileNotFoundException: class path resource [validation-rule.schema.json] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/dgcg.jar!/BOOT-INF/classes!/validation-rule.schema.json`
=> Fix loading of Validation Rule Schema from classpath

src/main/java/eu/europa/ec/dgc/gateway/service/ValidationRuleService.java, src/test/java/eu/europa/ec/dgc/gateway/restapi/controller/ValidationRuleIntegrationTest.java, src/test/java/eu/europa/ec/dgc/gateway/testdata/CertificateTestUtils.java
This PR adds the ValidationRule Check on upload that the CertificateType property matches the used prefix in the id.
See #104 for the mapping.
closes #104
=> Add ValidationRule Check for CertificateType

src/main/java/eu/europa/ec/dgc/gateway/service/ValidationRuleService.java, src/test/java/eu/europa/ec/dgc/gateway/restapi/controller/ValidationRuleIntegrationTest.java
This PR fixes a bug, that it is possible to append any string to the JSON when uploading a validation rule.
=> Fix: Validation Rule Upload Trailing Characters

pom.xml
Update to SpringBoot 2.6.6 to mitigate https://tanzu.vmware.com/security/cve-2022-22965
=> Chore: Update SpringBoot 2.6.6

src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/TrustListController.java, src/test/java/eu/europa/ec/dgc/gateway/restapi/controller/TrustListIntegrationTest.java
This PR fixes Pagination for TrustList Pagination if only pagesize OR page is provided.
fixes #192
=> Fix: Fallback Values for Pagination

src/main/resources/publication/Readme.txt
This PR changes the ```openssl cms -verify``` to output the binary stream to Windows' NUL-Stream instead of temporary file.
=> Feat: Improve Verify Command for Windows in Publication doc

src/main/java/eu/europa/ec/dgc/gateway/model/JrcRatValuesetResponse.java, src/main/java/eu/europa/ec/dgc/gateway/service/RatValuesetUpdateService.java, src/test/java/eu/europa/ec/dgc/gateway/service/RatValuesetUpdateServiceTest.java
This reverts commit ee51852ff9e722912dcf607919cd6b6447cbd1e9.
=> Fix: Revert "Fix: New JRC Format (#193)"

owasp/suppressions.xml, src/test/java/eu/europa/ec/dgc/gateway/service/SignerInformationServiceTest.java
This PR fixes a Unit-Test which failes sometimes because of millisecond part of the used timestamps.
fixes #189
=> Fix: Sporadic failing Unit-Test
