.github/workflows/ci-dependency-check.yml, .github/workflows/ci-master.yml, pom.xml, src/assembly/assembly.xml
Adjusted CI (GitHub Actions) to enable Deployment to Digit Data Center
=> CI for DIGIT Deployment

.github/workflows/ci-main.yml, .github/workflows/ci-pull-request.yml, .github/workflows/ci-release-notes.yml, .github/workflows/ci-sonar-check.yml, README.md, pom.xml, src/main/java/eu/europa/ec/dgc/gateway/service/SignerInformationService.java, src/test/java/eu/europa/ec/dgc/gateway/restapi/controller/SignerCertificateIntegrationTest.java, src/test/java/eu/europa/ec/dgc/gateway/restapi/controller/TrustListIntegrationTest.java, src/test/java/eu/europa/ec/dgc/gateway/restapi/filter/CertAuthFilterTest.java, src/test/java/eu/europa/ec/dgc/gateway/service/SignerInformationServiceTest.java, src/test/java/eu/europa/ec/dgc/gateway/service/TrustListServiceTest.java, src/test/java/eu/europa/ec/dgc/gateway/service/TrustedPartyServiceTest.java, src/test/java/eu/europa/ec/dgc/gateway/testdata/DgcTestKeyStore.java
Added SonarCloud Check to GitHub CI Actions
=> Add SonarCloud Check

.github/workflows/ci-release.yml, pom.xml
I've added a step in CI to automatically generate Swagger-JSON file on release. This file will be added as artifact to release.
closes #9
=> Add automatic Swagger Doc creation

.gitignore, README.md, docker-compose.yml, src/main/resources/logback-spring.xml
I've added some documentation about running the gateway locally.
=> Readme Local Deployment

pom.xml
This PR contains a updated version of coverage exlusion. Nonfunctional classes like Models and Repositories are now excluded.
=> Sonar Coverage Exclusion

docs/software-design-dgc-gateway.md, src/main/java/eu/europa/ec/dgc/gateway/config/ErrorHandler.java, src/main/java/eu/europa/ec/dgc/gateway/exception/DgcgResponseException.java, src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/SignerCertificateController.java, src/main/java/eu/europa/ec/dgc/gateway/restapi/dto/ProblemReportDto.java
This PR implements the Problem Report Feature
=> feat(#10)/Added Problem Reports

README.md
@f11h sorry I just saw a couple of typos just after you merged my last PR :(
I also added a section over converting the keys.
=> Fixed typos + added PKCS#12 section for Windows users.

pom.xml, src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/TrustListController.java, src/main/java/eu/europa/ec/dgc/gateway/restapi/mapper/GwTrustListMapper.java
Update DGC-Lib to 0.4.2
Rename TrustListMapper to avoid conflict with Mapper from DGC Lib
=> Update DGC Lib

docs/software-design-dgc-gateway.md, src/main/java/eu/europa/ec/dgc/gateway/config/ErrorHandler.java, src/main/java/eu/europa/ec/dgc/gateway/config/MdcCleanupInterceptor.java, src/main/java/eu/europa/ec/dgc/gateway/config/WebMvcConfig.java, src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/SignerCertificateController.java, src/main/java/eu/europa/ec/dgc/gateway/service/AuditService.java, src/main/java/eu/europa/ec/dgc/gateway/service/SignerInformationService.java, src/main/java/eu/europa/ec/dgc/gateway/service/TrustedPartyService.java, src/main/resources/logback-spring.xml
This PR fixes the problem that file log-output has some unwanted line breaks.
Also this PR adds a description of the existing log messages.
In Addition a new Interceptor to cleanup the MDC after each request is added.
=> Fix: Newline in Logging

docs/software-design-dgc-gateway.md, src/main/java/eu/europa/ec/dgc/gateway/repository/SignerInformationRepository.java, src/main/java/eu/europa/ec/dgc/gateway/service/SignerInformationService.java, src/test/java/eu/europa/ec/dgc/gateway/service/SignerInformationServiceTest.java
Add Check for Double KID when uploading certificate
=> Add Check for Double KID

pom.xml
- springdoc-openapi-ui:1.5.7->1.5.8
=> fix: update vulnerable dependencies

src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/SignerCertificateController.java
Replaced "Revoke" by "Delete" in delete endpoint.
=> Change OpenAPI Delete Endpoint Wording

docs/software-design-dgc-gateway.md, pom.xml, src/main/java/eu/europa/ec/dgc/gateway/entity/ValuesetEntity.java, src/main/java/eu/europa/ec/dgc/gateway/repository/ValuesetRepository.java, src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/ValuesetController.java, src/main/java/eu/europa/ec/dgc/gateway/service/ValuesetService.java, src/main/resources/db/changelog.xml, src/main/resources/db/changelog/add-valueset-table.xml, src/main/resources/db/snapshot.json, src/test/java/eu/europa/ec/dgc/gateway/restapi/controller/ValuesetIntegrationTest.java, src/test/java/eu/europa/ec/dgc/gateway/service/ValuesetServiceTest.java
This PR adds the ability to distribute JSON Valuesets via the Gateway.
This PR closes #78
=> Add Valueset Feature

src/main/java/eu/europa/ec/dgc/gateway/config/ErrorHandler.java, src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/SignerCertificateController.java, src/main/java/eu/europa/ec/dgc/gateway/restapi/converter/CmsMessageConverter.java, src/main/java/eu/europa/ec/dgc/gateway/restapi/filter/CertificateAuthenticationFilter.java, src/test/java/eu/europa/ec/dgc/gateway/restapi/controller/SignerCertificateIntegrationTest.java
This PR fixes a missing CMS Signature Validation.
=> Fix: Missing CMS Signature Validation

pom.xml, src/main/java/eu/europa/ec/dgc/gateway/restapi/dto/TrustListDto.java
Fix Timestamp Format for TrustList Download
Update DGC-Lib to 1.1.1
=> Timestamp Fix and DGC-Lib Update

src/main/java/eu/europa/ec/dgc/gateway/restapi/filter/CertificateAuthenticationFilter.java
This PR replaces the HEX-Parser/Encoder in CertificateAuthentication Filter to use the BouncyCastle one.
This PR is related to #99
=> Replace HEX-Parser/Encoder in CertificateAuthenticationFilter

src/main/java/eu/europa/ec/dgc/gateway/service/ValidationRuleService.java, src/test/java/eu/europa/ec/dgc/gateway/restapi/controller/ValidationRuleIntegrationTest.java
Add Rule Validation to Check that rule is at least 72h valid.
This PR closes #100
=> Fix ValidationRule Check: Rule is at least 72h valid

src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/CertificateRevocationListController.java, src/test/java/eu/europa/ec/dgc/gateway/restapi/controller/CertificateRevocationListIntegrationTest.java
Batch ID of uploaded Revocation List will be returned in ETag Header
=> Feat: Return Batch ID on Revocation List Upload

src/main/java/eu/europa/ec/dgc/gateway/config/ValidationRuleSchemaProvider.java, src/main/java/eu/europa/ec/dgc/gateway/entity/TrustedPartyEntity.java, src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/CertificateRevocationListController.java, src/main/java/eu/europa/ec/dgc/gateway/restapi/filter/CertificateAuthenticationFilter.java, src/main/java/eu/europa/ec/dgc/gateway/restapi/filter/CertificateAuthenticationRole.java, src/main/java/eu/europa/ec/dgc/gateway/restapi/mapper/CertificateRoleMapper.java, src/main/resources/db/changelog.xml, src/main/resources/db/changelog/add-certificate-roles-table.xml, src/main/resources/db/snapshot.json, src/test/java/eu/europa/ec/dgc/gateway/restapi/controller/CertificateRevocationListIntegrationTest.java, src/test/java/eu/europa/ec/dgc/gateway/testdata/TrustedPartyTestHelper.java
This PR adds a required authorisation for the revocation list endpoints. This feature is required to control who is allowed to publish and read revocation data.
=> Feat: Authorisation for Revocation Endpoints

pom.xml
Include Hibernate Dependencie to support H2 2.x
Update DGC-Lib
=> Chore: Update H2 Dependencies and DGC Lib

pom.xml
- spring boot 2.6.4
- liquibase 4.8.0
- spring security 5.6.2
- dgc-lib 1.2.0
=> deps: bump dependencies

src/main/java/eu/europa/ec/dgc/gateway/service/SignerInformationService.java, src/test/java/eu/europa/ec/dgc/gateway/restapi/controller/CertificateMigrationControllerTest.java
Related to issue https://github.com/eu-digital-green-certificates/dgc-gateway/issues/163
=> fix return value for cms migration of signer information

src/main/java/eu/europa/ec/dgc/gateway/service/RevocationListService.java, src/test/java/eu/europa/ec/dgc/gateway/restapi/controller/CertificateMigrationControllerTest.java
Related to issue https://github.com/eu-digital-green-certificates/dgc-gateway/issues/164
=> feat: revocation batches marked for deletion are not returned for migration

pom.xml, src/main/java/eu/europa/ec/dgc/gateway/config/DgcConfigProperties.java, src/main/java/eu/europa/ec/dgc/gateway/entity/SignerInformationEntity.java, src/main/java/eu/europa/ec/dgc/gateway/repository/SignerInformationRepository.java, src/main/java/eu/europa/ec/dgc/gateway/repository/TrustedPartyRepository.java, src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/TrustListController.java, src/main/java/eu/europa/ec/dgc/gateway/service/SignerInformationCleanUpService.java, src/main/java/eu/europa/ec/dgc/gateway/service/SignerInformationService.java, src/main/java/eu/europa/ec/dgc/gateway/service/TrustListService.java, src/main/java/eu/europa/ec/dgc/gateway/service/TrustedPartyService.java, src/main/java/eu/europa/ec/dgc/gateway/utils/ListUtils.java, src/main/resources/application.yml, src/main/resources/db/changelog.xml, src/main/resources/db/changelog/alter-signer-information-for-deletion.xml, src/test/java/eu/europa/ec/dgc/gateway/restapi/controller/CertificateMigrationControllerTest.java, src/test/java/eu/europa/ec/dgc/gateway/restapi/controller/TrustListIntegrationTest.java, src/test/java/eu/europa/ec/dgc/gateway/service/SignerInformationCleanUpServiceTest.java, src/test/java/eu/europa/ec/dgc/gateway/service/SignerInformationServiceTest.java, src/test/java/eu/europa/ec/dgc/gateway/service/TrustListServiceTest.java, src/test/java/eu/europa/ec/dgc/gateway/service/TrustedPartyServiceTest.java, src/test/java/eu/europa/ec/dgc/gateway/testdata/SignerInformationTestHelper.java, src/test/java/eu/europa/ec/dgc/gateway/testdata/TrustedPartyTestHelper.java
feature implemented without deletion, which is in #166
=> feat: dsc delta download extension

pom.xml, src/main/java/eu/europa/ec/dgc/gateway/restapi/converter/CmsCertificateMessageConverter.java, src/main/java/eu/europa/ec/dgc/gateway/restapi/dto/CmsPackageDto.java, src/main/java/eu/europa/ec/dgc/gateway/service/SignerInformationService.java, src/test/java/eu/europa/ec/dgc/gateway/restapi/controller/CertificateMigrationControllerTest.java
=> Fix: Add Embedded Signature for DSC Migration

pom.xml, src/main/java/eu/europa/ec/dgc/gateway/repository/SignerInformationRepository.java, src/main/java/eu/europa/ec/dgc/gateway/service/SignerInformationService.java, src/test/java/eu/europa/ec/dgc/gateway/service/SignerInformationServiceTest.java
Include deleted SignerInformation only if isModifiedSince is set, part 2
=> Fix remove deleted certificates from response

src/main/java/eu/europa/ec/dgc/gateway/repository/SignerInformationRepository.java, src/main/java/eu/europa/ec/dgc/gateway/service/SignerInformationService.java, src/test/java/eu/europa/ec/dgc/gateway/restapi/controller/SignerCertificateIntegrationTest.java
=> Fix: Reupload of DSC

docker-compose.yml, lombok.config, src/main/java/eu/europa/ec/dgc/gateway/client/AssetManagerClient.java, src/main/java/eu/europa/ec/dgc/gateway/client/AssetManagerClientConfig.java, src/main/java/eu/europa/ec/dgc/gateway/config/DgcConfigProperties.java, src/main/java/eu/europa/ec/dgc/gateway/config/DgcKeyStore.java, src/main/java/eu/europa/ec/dgc/gateway/model/AssetManagerSynchronizeResponseDto.java, src/main/java/eu/europa/ec/dgc/gateway/service/PublishingService.java, src/main/java/eu/europa/ec/dgc/gateway/service/TrustedIssuerService.java, src/main/java/eu/europa/ec/dgc/gateway/service/TrustedPartyService.java, src/main/resources/application.yml, src/main/resources/publication/License.txt, src/main/resources/publication/Readme.txt, src/test/java/eu/europa/ec/dgc/gateway/publishing/ArchivePublishingTest.java, src/test/java/eu/europa/ec/dgc/gateway/publishing/PublishingDisabledTest.java, src/test/java/eu/europa/ec/dgc/gateway/testdata/DgcTestKeyStore.java, src/test/java/eu/europa/ec/dgc/gateway/testdata/TrustedIssuerTestHelper.java, src/test/java/eu/europa/ec/dgc/gateway/testdata/TrustedPartyTestHelper.java, src/test/resources/application.yml
Add feature to provide ZIP archive with all uploaded DSC and CSCA certificates.
=> Feat: Publication

owasp/suppressions.xml, pom.xml, src/main/java/eu/europa/ec/dgc/gateway/entity/ValidationRuleEntity.java, src/main/resources/db/changelog.xml, src/main/resources/db/changelog/increase-column-size-for-validation-rule-signature.xml
including dependency updates:
- spring boot 2.6.8
- spring security 5.6.5
- h2 2.1.212
=> Increase column size for validation rule signature to max 20_000

owasp/suppressions.xml, pom.xml
To migitate open OWASP issues.
=> Chore: Update Dependencies

src/main/java/eu/europa/ec/dgc/gateway/model/RevocationBatchDownload.java, src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/CertificateRevocationListController.java, src/main/java/eu/europa/ec/dgc/gateway/service/RevocationListService.java
This PR adds a log message for revocation batch download.
=> Feat: Add log for Revocation Batch Download

README.md
=> doc: modified  README.md

src/main/java/eu/europa/ec/dgc/gateway/service/PublishingService.java
=> Fix: Name of DCCG in Version.txt File of publication archive

src/main/java/eu/europa/ec/dgc/gateway/repository/SignerInformationRepository.java, src/main/java/eu/europa/ec/dgc/gateway/repository/TrustedPartyRepository.java, src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/CertificateRevocationListController.java, src/main/java/eu/europa/ec/dgc/gateway/restapi/filter/CertificateAuthenticationFilter.java, src/main/java/eu/europa/ec/dgc/gateway/restapi/filter/IpLoggingFilter.java, src/test/java/eu/europa/ec/dgc/gateway/publishing/ArchivePublishingTest.java, src/test/java/eu/europa/ec/dgc/gateway/restapi/controller/CertificateRevocationListIntegrationTest.java, src/test/java/eu/europa/ec/dgc/gateway/restapi/controller/TrustListIntegrationTest.java, src/test/java/eu/europa/ec/dgc/gateway/service/SignerInformationCleanUpServiceTest.java, src/test/java/eu/europa/ec/dgc/gateway/service/ValuesetServiceTest.java
Add filter to put Request IP in MDC
=> Feat: Log Request IP

pom.xml, src/main/java/eu/europa/ec/dgc/gateway/entity/RevocationBatchEntity.java, src/main/java/eu/europa/ec/dgc/gateway/entity/ValuesetEntity.java, src/main/resources/application-h2.yml, src/main/resources/application-mysql.yml, src/main/resources/application.yml
Remove explicit SQL Dialect
Add Hibernate Datatype to ensure compatibility with MySQL
=> Fix: SQL Dialect

owasp/suppressions.xml, src/main/java/eu/europa/ec/dgc/gateway/restapi/controller/CertificateRevocationListController.java, src/main/java/eu/europa/ec/dgc/gateway/service/RevocationListService.java, src/test/java/eu/europa/ec/dgc/gateway/restapi/controller/CertificateRevocationListIntegrationTest.java
=> Fix: Revocation Date must be in future

README.md
=> Doc: Remove Mail.Ru Logo

.gitignore, owasp/suppressions.xml, pom.xml
=> Feat: Dependency Update
